---
theme: jekyll-theme-minimal
title: Resource Center KE
description: >- # this means to ignore newlines until "baseurl:"
  A collection of resources for developers in Kenya.
baseurl: "/ResourceCenter-KE/"
url: "https://Hezekiah-Elisha.github.io"
twitter_username: _hezekiahelisha
github_username: Hezekiah-Elisha
email: elishahezekiah903@gmail.com

# Additional configurations
author: Hezekiah Elisha
paginate: 5
permalink: pretty
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Include additional files
include:
  - _pages

# Social media links
social_links:
  linkedin: https://www.linkedin.com/in/hezekiah-elisha
  github: https://github.com/Hezekiah-Elisha
  twitter: https://twitter.com/_hezekiahelisha