---
theme: jekyll-theme-minimal
title: Resource Center KE
description: >- # this means to ignore newlines until "baseurl:"
  A collection of resources for developers in Kenya.
baseurl: "/ResourceCenter-KE/"
url: "https://Hezekiah-Elisha.github.io"
twitter_username: _hezekiahelisha
github_username:  Hezekiah-Elisha
email: elishahezekiah903@gmail.com
